name: ClearChat
main: me.onetwoeight.clearchat.Main
version: $version
website: https://github.com/128931/ClearChat
description: Plugin for clearing a player's chat or global chat
author: '12893'
api-version: 1.13
commands:
  cc:
    description: Clears a player's chat or global chat
    usage: /<command>
    aliases: [ clearchat ]
