main: me.onetwoeight.clearchat.Main
name: ClearChat
version: $version
description: Plugin for clearing a player's chat or global chat
load: STARTUP
author: '12893'
website: https://github.com/128931/ClearChat
api-version: 1.13
commands:
  cc:
    description: Clears a player's chat or global chat
    aliases:
      - clearchat
    usage: /<command>